package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdvertisingLocation generated by hbm2java
 */
public class AdvertisingLocation  implements java.io.Serializable {


     private Integer idadvertisingLocation;
     private String imgSize;
     private String location;
     private Double price;
     private Double discount;
     private Set advertisings = new HashSet(0);

    public AdvertisingLocation() {
    }

    public AdvertisingLocation(String imgSize, String location, Double price, Double discount, Set advertisings) {
       this.imgSize = imgSize;
       this.location = location;
       this.price = price;
       this.discount = discount;
       this.advertisings = advertisings;
    }
   
    public Integer getIdadvertisingLocation() {
        return this.idadvertisingLocation;
    }
    
    public void setIdadvertisingLocation(Integer idadvertisingLocation) {
        this.idadvertisingLocation = idadvertisingLocation;
    }
    public String getImgSize() {
        return this.imgSize;
    }
    
    public void setImgSize(String imgSize) {
        this.imgSize = imgSize;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Set getAdvertisings() {
        return this.advertisings;
    }
    
    public void setAdvertisings(Set advertisings) {
        this.advertisings = advertisings;
    }




}


