package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * Advertising generated by hbm2java
 */
public class Advertising  implements java.io.Serializable {


     private Integer idadvertising;
     private AdvertisingCategory advertisingCategory;
     private AdvertisingDatePlans advertisingDatePlans;
     private AdvertisingLocation advertisingLocation;
     private AdvertisingStatus advertisingStatus;
     private User user;
     private String addTitle;
     private Date onDate;
     private String description;
     private String imgUrl;
     private String websiteUrl;

    public Advertising() {
    }

	
    public Advertising(AdvertisingCategory advertisingCategory, AdvertisingDatePlans advertisingDatePlans, AdvertisingLocation advertisingLocation, AdvertisingStatus advertisingStatus, User user) {
        this.advertisingCategory = advertisingCategory;
        this.advertisingDatePlans = advertisingDatePlans;
        this.advertisingLocation = advertisingLocation;
        this.advertisingStatus = advertisingStatus;
        this.user = user;
    }
    public Advertising(AdvertisingCategory advertisingCategory, AdvertisingDatePlans advertisingDatePlans, AdvertisingLocation advertisingLocation, AdvertisingStatus advertisingStatus, User user, String addTitle, Date onDate, String description, String imgUrl, String websiteUrl) {
       this.advertisingCategory = advertisingCategory;
       this.advertisingDatePlans = advertisingDatePlans;
       this.advertisingLocation = advertisingLocation;
       this.advertisingStatus = advertisingStatus;
       this.user = user;
       this.addTitle = addTitle;
       this.onDate = onDate;
       this.description = description;
       this.imgUrl = imgUrl;
       this.websiteUrl = websiteUrl;
    }
   
    public Integer getIdadvertising() {
        return this.idadvertising;
    }
    
    public void setIdadvertising(Integer idadvertising) {
        this.idadvertising = idadvertising;
    }
    public AdvertisingCategory getAdvertisingCategory() {
        return this.advertisingCategory;
    }
    
    public void setAdvertisingCategory(AdvertisingCategory advertisingCategory) {
        this.advertisingCategory = advertisingCategory;
    }
    public AdvertisingDatePlans getAdvertisingDatePlans() {
        return this.advertisingDatePlans;
    }
    
    public void setAdvertisingDatePlans(AdvertisingDatePlans advertisingDatePlans) {
        this.advertisingDatePlans = advertisingDatePlans;
    }
    public AdvertisingLocation getAdvertisingLocation() {
        return this.advertisingLocation;
    }
    
    public void setAdvertisingLocation(AdvertisingLocation advertisingLocation) {
        this.advertisingLocation = advertisingLocation;
    }
    public AdvertisingStatus getAdvertisingStatus() {
        return this.advertisingStatus;
    }
    
    public void setAdvertisingStatus(AdvertisingStatus advertisingStatus) {
        this.advertisingStatus = advertisingStatus;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getAddTitle() {
        return this.addTitle;
    }
    
    public void setAddTitle(String addTitle) {
        this.addTitle = addTitle;
    }
    public Date getOnDate() {
        return this.onDate;
    }
    
    public void setOnDate(Date onDate) {
        this.onDate = onDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
    public String getWebsiteUrl() {
        return this.websiteUrl;
    }
    
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }




}


