package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdvertisingStatus generated by hbm2java
 */
public class AdvertisingStatus  implements java.io.Serializable {


     private Integer idadvertisingStatus;
     private String status;
     private Set advertisingDatePlanses = new HashSet(0);
     private Set advertisingCategories = new HashSet(0);
     private Set coverPhotoses = new HashSet(0);
     private Set advertisings = new HashSet(0);

    public AdvertisingStatus() {
    }

    public AdvertisingStatus(String status, Set advertisingDatePlanses, Set advertisingCategories, Set coverPhotoses, Set advertisings) {
       this.status = status;
       this.advertisingDatePlanses = advertisingDatePlanses;
       this.advertisingCategories = advertisingCategories;
       this.coverPhotoses = coverPhotoses;
       this.advertisings = advertisings;
    }
   
    public Integer getIdadvertisingStatus() {
        return this.idadvertisingStatus;
    }
    
    public void setIdadvertisingStatus(Integer idadvertisingStatus) {
        this.idadvertisingStatus = idadvertisingStatus;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getAdvertisingDatePlanses() {
        return this.advertisingDatePlanses;
    }
    
    public void setAdvertisingDatePlanses(Set advertisingDatePlanses) {
        this.advertisingDatePlanses = advertisingDatePlanses;
    }
    public Set getAdvertisingCategories() {
        return this.advertisingCategories;
    }
    
    public void setAdvertisingCategories(Set advertisingCategories) {
        this.advertisingCategories = advertisingCategories;
    }
    public Set getCoverPhotoses() {
        return this.coverPhotoses;
    }
    
    public void setCoverPhotoses(Set coverPhotoses) {
        this.coverPhotoses = coverPhotoses;
    }
    public Set getAdvertisings() {
        return this.advertisings;
    }
    
    public void setAdvertisings(Set advertisings) {
        this.advertisings = advertisings;
    }




}


