package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdvertisingCategory generated by hbm2java
 */
public class AdvertisingCategory  implements java.io.Serializable {


     private Integer idadvertisingCategory;
     private AdvertisingStatus advertisingStatus;
     private String category;
     private Set advertisings = new HashSet(0);

    public AdvertisingCategory() {
    }

	
    public AdvertisingCategory(AdvertisingStatus advertisingStatus) {
        this.advertisingStatus = advertisingStatus;
    }
    public AdvertisingCategory(AdvertisingStatus advertisingStatus, String category, Set advertisings) {
       this.advertisingStatus = advertisingStatus;
       this.category = category;
       this.advertisings = advertisings;
    }
   
    public Integer getIdadvertisingCategory() {
        return this.idadvertisingCategory;
    }
    
    public void setIdadvertisingCategory(Integer idadvertisingCategory) {
        this.idadvertisingCategory = idadvertisingCategory;
    }
    public AdvertisingStatus getAdvertisingStatus() {
        return this.advertisingStatus;
    }
    
    public void setAdvertisingStatus(AdvertisingStatus advertisingStatus) {
        this.advertisingStatus = advertisingStatus;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Set getAdvertisings() {
        return this.advertisings;
    }
    
    public void setAdvertisings(Set advertisings) {
        this.advertisings = advertisings;
    }




}


