package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdvertisingDatePlans generated by hbm2java
 */
public class AdvertisingDatePlans  implements java.io.Serializable {


     private Integer idadvertisingDatePlans;
     private AdvertisingStatus advertisingStatus;
     private Integer dateCount;
     private String pakage;
     private Double price;
     private Double discount;
     private Set advertisings = new HashSet(0);

    public AdvertisingDatePlans() {
    }

	
    public AdvertisingDatePlans(AdvertisingStatus advertisingStatus) {
        this.advertisingStatus = advertisingStatus;
    }
    public AdvertisingDatePlans(AdvertisingStatus advertisingStatus, Integer dateCount, String pakage, Double price, Double discount, Set advertisings) {
       this.advertisingStatus = advertisingStatus;
       this.dateCount = dateCount;
       this.pakage = pakage;
       this.price = price;
       this.discount = discount;
       this.advertisings = advertisings;
    }
   
    public Integer getIdadvertisingDatePlans() {
        return this.idadvertisingDatePlans;
    }
    
    public void setIdadvertisingDatePlans(Integer idadvertisingDatePlans) {
        this.idadvertisingDatePlans = idadvertisingDatePlans;
    }
    public AdvertisingStatus getAdvertisingStatus() {
        return this.advertisingStatus;
    }
    
    public void setAdvertisingStatus(AdvertisingStatus advertisingStatus) {
        this.advertisingStatus = advertisingStatus;
    }
    public Integer getDateCount() {
        return this.dateCount;
    }
    
    public void setDateCount(Integer dateCount) {
        this.dateCount = dateCount;
    }
    public String getPakage() {
        return this.pakage;
    }
    
    public void setPakage(String pakage) {
        this.pakage = pakage;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Set getAdvertisings() {
        return this.advertisings;
    }
    
    public void setAdvertisings(Set advertisings) {
        this.advertisings = advertisings;
    }




}


