package pojo;
// Generated Jan 23, 2016 3:21:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand  implements java.io.Serializable {


     private Integer idbrand;
     private String brandName;
     private Set products = new HashSet(0);

    public Brand() {
    }

    public Brand(String brandName, Set products) {
       this.brandName = brandName;
       this.products = products;
    }
   
    public Integer getIdbrand() {
        return this.idbrand;
    }
    
    public void setIdbrand(Integer idbrand) {
        this.idbrand = idbrand;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


