package pojo;
// Generated Jan 23, 2016 3:21:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer idcart;
     private User user;
     private Integer productCount;
     private Double totalAmount;
     private Set cartHasProductses = new HashSet(0);
     private Set invoices = new HashSet(0);

    public Cart() {
    }

	
    public Cart(User user) {
        this.user = user;
    }
    public Cart(User user, Integer productCount, Double totalAmount, Set cartHasProductses, Set invoices) {
       this.user = user;
       this.productCount = productCount;
       this.totalAmount = totalAmount;
       this.cartHasProductses = cartHasProductses;
       this.invoices = invoices;
    }
   
    public Integer getIdcart() {
        return this.idcart;
    }
    
    public void setIdcart(Integer idcart) {
        this.idcart = idcart;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getProductCount() {
        return this.productCount;
    }
    
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Set getCartHasProductses() {
        return this.cartHasProductses;
    }
    
    public void setCartHasProductses(Set cartHasProductses) {
        this.cartHasProductses = cartHasProductses;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


