package pojo;
// Generated Jan 23, 2016 3:21:10 PM by Hibernate Tools 4.3.1



/**
 * CartHasProducts generated by hbm2java
 */
public class CartHasProducts  implements java.io.Serializable {


     private Integer idcartHasProducts;
     private Cart cart;
     private Product product;
     private Integer qty;
     private Integer isPurchased;
     private Double amount;

    public CartHasProducts() {
    }

	
    public CartHasProducts(Cart cart, Product product) {
        this.cart = cart;
        this.product = product;
    }
    public CartHasProducts(Cart cart, Product product, Integer qty, Integer isPurchased, Double amount) {
       this.cart = cart;
       this.product = product;
       this.qty = qty;
       this.isPurchased = isPurchased;
       this.amount = amount;
    }
   
    public Integer getIdcartHasProducts() {
        return this.idcartHasProducts;
    }
    
    public void setIdcartHasProducts(Integer idcartHasProducts) {
        this.idcartHasProducts = idcartHasProducts;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Integer getIsPurchased() {
        return this.isPurchased;
    }
    
    public void setIsPurchased(Integer isPurchased) {
        this.isPurchased = isPurchased;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }




}


