package pojo;
// Generated Jan 23, 2016 3:21:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Catagory generated by hbm2java
 */
public class Catagory  implements java.io.Serializable {


     private Integer idcatagory;
     private String catagory;
     private Set subCategories = new HashSet(0);

    public Catagory() {
    }

    public Catagory(String catagory, Set subCategories) {
       this.catagory = catagory;
       this.subCategories = subCategories;
    }
   
    public Integer getIdcatagory() {
        return this.idcatagory;
    }
    
    public void setIdcatagory(Integer idcatagory) {
        this.idcatagory = idcatagory;
    }
    public String getCatagory() {
        return this.catagory;
    }
    
    public void setCatagory(String catagory) {
        this.catagory = catagory;
    }
    public Set getSubCategories() {
        return this.subCategories;
    }
    
    public void setSubCategories(Set subCategories) {
        this.subCategories = subCategories;
    }




}


