package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1



/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Integer idcompanies;
     private String name;
     private String email;
     private String bizType;
     private String websiteUrl;

    public Company() {
    }

    public Company(String name, String email, String bizType, String websiteUrl) {
       this.name = name;
       this.email = email;
       this.bizType = bizType;
       this.websiteUrl = websiteUrl;
    }
   
    public Integer getIdcompanies() {
        return this.idcompanies;
    }
    
    public void setIdcompanies(Integer idcompanies) {
        this.idcompanies = idcompanies;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getBizType() {
        return this.bizType;
    }
    
    public void setBizType(String bizType) {
        this.bizType = bizType;
    }
    public String getWebsiteUrl() {
        return this.websiteUrl;
    }
    
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }




}


