package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1



/**
 * CoverPhotos generated by hbm2java
 */
public class CoverPhotos  implements java.io.Serializable {


     private Integer idcoverPhotos;
     private AdvertisingStatus advertisingStatus;
     private String code;
     private String imgUrl;

    public CoverPhotos() {
    }

	
    public CoverPhotos(AdvertisingStatus advertisingStatus) {
        this.advertisingStatus = advertisingStatus;
    }
    public CoverPhotos(AdvertisingStatus advertisingStatus, String code, String imgUrl) {
       this.advertisingStatus = advertisingStatus;
       this.code = code;
       this.imgUrl = imgUrl;
    }
   
    public Integer getIdcoverPhotos() {
        return this.idcoverPhotos;
    }
    
    public void setIdcoverPhotos(Integer idcoverPhotos) {
        this.idcoverPhotos = idcoverPhotos;
    }
    public AdvertisingStatus getAdvertisingStatus() {
        return this.advertisingStatus;
    }
    
    public void setAdvertisingStatus(AdvertisingStatus advertisingStatus) {
        this.advertisingStatus = advertisingStatus;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }




}


