package pojo;
// Generated Jan 23, 2016 3:21:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DeliveryPlan generated by hbm2java
 */
public class DeliveryPlan  implements java.io.Serializable {


     private Integer iddeliveryPlan;
     private String name;
     private Double k10;
     private Double k50;
     private Double k100;
     private Double k100up;
     private Integer deliveryPeriod;
     private String description;
     private Set deliveries = new HashSet(0);

    public DeliveryPlan() {
    }

    public DeliveryPlan(String name, Double k10, Double k50, Double k100, Double k100up, Integer deliveryPeriod, String description, Set deliveries) {
       this.name = name;
       this.k10 = k10;
       this.k50 = k50;
       this.k100 = k100;
       this.k100up = k100up;
       this.deliveryPeriod = deliveryPeriod;
       this.description = description;
       this.deliveries = deliveries;
    }
   
    public Integer getIddeliveryPlan() {
        return this.iddeliveryPlan;
    }
    
    public void setIddeliveryPlan(Integer iddeliveryPlan) {
        this.iddeliveryPlan = iddeliveryPlan;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getK10() {
        return this.k10;
    }
    
    public void setK10(Double k10) {
        this.k10 = k10;
    }
    public Double getK50() {
        return this.k50;
    }
    
    public void setK50(Double k50) {
        this.k50 = k50;
    }
    public Double getK100() {
        return this.k100;
    }
    
    public void setK100(Double k100) {
        this.k100 = k100;
    }
    public Double getK100up() {
        return this.k100up;
    }
    
    public void setK100up(Double k100up) {
        this.k100up = k100up;
    }
    public Integer getDeliveryPeriod() {
        return this.deliveryPeriod;
    }
    
    public void setDeliveryPeriod(Integer deliveryPeriod) {
        this.deliveryPeriod = deliveryPeriod;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getDeliveries() {
        return this.deliveries;
    }
    
    public void setDeliveries(Set deliveries) {
        this.deliveries = deliveries;
    }




}


