package pojo;
// Generated Jan 23, 2016 3:21:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private Integer iddelivery;
     private DeliveryPlan deliveryPlan;
     private Invoice invoice;
     private User user;
     private String name;
     private String address1;
     private String address2;
     private String city;
     private String state;
     private String postalCode;
     private Double cost;
     private Date shippingDate;

    public Delivery() {
    }

	
    public Delivery(DeliveryPlan deliveryPlan, Invoice invoice, User user) {
        this.deliveryPlan = deliveryPlan;
        this.invoice = invoice;
        this.user = user;
    }
    public Delivery(DeliveryPlan deliveryPlan, Invoice invoice, User user, String name, String address1, String address2, String city, String state, String postalCode, Double cost, Date shippingDate) {
       this.deliveryPlan = deliveryPlan;
       this.invoice = invoice;
       this.user = user;
       this.name = name;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.state = state;
       this.postalCode = postalCode;
       this.cost = cost;
       this.shippingDate = shippingDate;
    }
   
    public Integer getIddelivery() {
        return this.iddelivery;
    }
    
    public void setIddelivery(Integer iddelivery) {
        this.iddelivery = iddelivery;
    }
    public DeliveryPlan getDeliveryPlan() {
        return this.deliveryPlan;
    }
    
    public void setDeliveryPlan(DeliveryPlan deliveryPlan) {
        this.deliveryPlan = deliveryPlan;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public Date getShippingDate() {
        return this.shippingDate;
    }
    
    public void setShippingDate(Date shippingDate) {
        this.shippingDate = shippingDate;
    }




}


