package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Donations generated by hbm2java
 */
public class Donations  implements java.io.Serializable {


     private Integer iddonations;
     private DonationOrgs donationOrgs;
     private User user;
     private String amount;
     private Date date;
     private String reciptNum;

    public Donations() {
    }

	
    public Donations(DonationOrgs donationOrgs, User user) {
        this.donationOrgs = donationOrgs;
        this.user = user;
    }
    public Donations(DonationOrgs donationOrgs, User user, String amount, Date date, String reciptNum) {
       this.donationOrgs = donationOrgs;
       this.user = user;
       this.amount = amount;
       this.date = date;
       this.reciptNum = reciptNum;
    }
   
    public Integer getIddonations() {
        return this.iddonations;
    }
    
    public void setIddonations(Integer iddonations) {
        this.iddonations = iddonations;
    }
    public DonationOrgs getDonationOrgs() {
        return this.donationOrgs;
    }
    
    public void setDonationOrgs(DonationOrgs donationOrgs) {
        this.donationOrgs = donationOrgs;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getReciptNum() {
        return this.reciptNum;
    }
    
    public void setReciptNum(String reciptNum) {
        this.reciptNum = reciptNum;
    }




}


