package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DonationOrgs generated by hbm2java
 */
public class DonationOrgs  implements java.io.Serializable {


     private Integer iddonationOrgs;
     private String name;
     private String wesiteUrl;
     private String desciption;
     private String email;
     private String type;
     private String accNum;
     private Set donationses = new HashSet(0);

    public DonationOrgs() {
    }

    public DonationOrgs(String name, String wesiteUrl, String desciption, String email, String type, String accNum, Set donationses) {
       this.name = name;
       this.wesiteUrl = wesiteUrl;
       this.desciption = desciption;
       this.email = email;
       this.type = type;
       this.accNum = accNum;
       this.donationses = donationses;
    }
   
    public Integer getIddonationOrgs() {
        return this.iddonationOrgs;
    }
    
    public void setIddonationOrgs(Integer iddonationOrgs) {
        this.iddonationOrgs = iddonationOrgs;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getWesiteUrl() {
        return this.wesiteUrl;
    }
    
    public void setWesiteUrl(String wesiteUrl) {
        this.wesiteUrl = wesiteUrl;
    }
    public String getDesciption() {
        return this.desciption;
    }
    
    public void setDesciption(String desciption) {
        this.desciption = desciption;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getAccNum() {
        return this.accNum;
    }
    
    public void setAccNum(String accNum) {
        this.accNum = accNum;
    }
    public Set getDonationses() {
        return this.donationses;
    }
    
    public void setDonationses(Set donationses) {
        this.donationses = donationses;
    }




}


