package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1



/**
 * EmailCode generated by hbm2java
 */
public class EmailCode  implements java.io.Serializable {


     private Integer idemailCode;
     private User user;
     private String code;
     private Integer state;

    public EmailCode() {
    }

	
    public EmailCode(User user) {
        this.user = user;
    }
    public EmailCode(User user, String code, Integer state) {
       this.user = user;
       this.code = code;
       this.state = state;
    }
   
    public Integer getIdemailCode() {
        return this.idemailCode;
    }
    
    public void setIdemailCode(Integer idemailCode) {
        this.idemailCode = idemailCode;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }




}


