package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Payments generated by hbm2java
 */
public class Payments  implements java.io.Serializable {


     private Integer idpayments;
     private PaymentTypes paymentTypes;
     private String tranactionCode;
     private Date date;
     private String accNum;
     private Double amount;
     private String reciptNum;

    public Payments() {
    }

	
    public Payments(PaymentTypes paymentTypes) {
        this.paymentTypes = paymentTypes;
    }
    public Payments(PaymentTypes paymentTypes, String tranactionCode, Date date, String accNum, Double amount, String reciptNum) {
       this.paymentTypes = paymentTypes;
       this.tranactionCode = tranactionCode;
       this.date = date;
       this.accNum = accNum;
       this.amount = amount;
       this.reciptNum = reciptNum;
    }
   
    public Integer getIdpayments() {
        return this.idpayments;
    }
    
    public void setIdpayments(Integer idpayments) {
        this.idpayments = idpayments;
    }
    public PaymentTypes getPaymentTypes() {
        return this.paymentTypes;
    }
    
    public void setPaymentTypes(PaymentTypes paymentTypes) {
        this.paymentTypes = paymentTypes;
    }
    public String getTranactionCode() {
        return this.tranactionCode;
    }
    
    public void setTranactionCode(String tranactionCode) {
        this.tranactionCode = tranactionCode;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getAccNum() {
        return this.accNum;
    }
    
    public void setAccNum(String accNum) {
        this.accNum = accNum;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getReciptNum() {
        return this.reciptNum;
    }
    
    public void setReciptNum(String reciptNum) {
        this.reciptNum = reciptNum;
    }




}


