package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaymentTypes generated by hbm2java
 */
public class PaymentTypes  implements java.io.Serializable {


     private Integer idpaymentTypes;
     private String type;
     private Set paymentses = new HashSet(0);

    public PaymentTypes() {
    }

    public PaymentTypes(String type, Set paymentses) {
       this.type = type;
       this.paymentses = paymentses;
    }
   
    public Integer getIdpaymentTypes() {
        return this.idpaymentTypes;
    }
    
    public void setIdpaymentTypes(Integer idpaymentTypes) {
        this.idpaymentTypes = idpaymentTypes;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getPaymentses() {
        return this.paymentses;
    }
    
    public void setPaymentses(Set paymentses) {
        this.paymentses = paymentses;
    }




}


