package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1



/**
 * Privilages generated by hbm2java
 */
public class Privilages  implements java.io.Serializable {


     private Integer idprivilages;
     private Interfaces interfaces;
     private UserType userType;

    public Privilages() {
    }

    public Privilages(Interfaces interfaces, UserType userType) {
       this.interfaces = interfaces;
       this.userType = userType;
    }
   
    public Integer getIdprivilages() {
        return this.idprivilages;
    }
    
    public void setIdprivilages(Integer idprivilages) {
        this.idprivilages = idprivilages;
    }
    public Interfaces getInterfaces() {
        return this.interfaces;
    }
    
    public void setInterfaces(Interfaces interfaces) {
        this.interfaces = interfaces;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }




}


