package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1



/**
 * ProductRating generated by hbm2java
 */
public class ProductRating  implements java.io.Serializable {


     private Integer idproductRating;
     private PVotes PVotes;
     private Product product;
     private User user;
     private Integer boughtCount;

    public ProductRating() {
    }

	
    public ProductRating(PVotes PVotes, Product product, User user) {
        this.PVotes = PVotes;
        this.product = product;
        this.user = user;
    }
    public ProductRating(PVotes PVotes, Product product, User user, Integer boughtCount) {
       this.PVotes = PVotes;
       this.product = product;
       this.user = user;
       this.boughtCount = boughtCount;
    }
   
    public Integer getIdproductRating() {
        return this.idproductRating;
    }
    
    public void setIdproductRating(Integer idproductRating) {
        this.idproductRating = idproductRating;
    }
    public PVotes getPVotes() {
        return this.PVotes;
    }
    
    public void setPVotes(PVotes PVotes) {
        this.PVotes = PVotes;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getBoughtCount() {
        return this.boughtCount;
    }
    
    public void setBoughtCount(Integer boughtCount) {
        this.boughtCount = boughtCount;
    }




}


