package pojo;
// Generated Jan 23, 2016 3:21:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idproduct;
     private Brand brand;
     private PStatus PStatus;
     private ProductColor productColor;
     private SubCategory subCategory;
     private String productCode;
     private String name;
     private Double price;
     private Double discount;
     private Integer qty;
     private Integer reoderLevel;
     private Double weight;
     private String imageUrl1;
     private String imageUrl2;
     private String imageUrl3;
     private String description;
     private Date regDate;
     private Set cartHasProductses = new HashSet(0);

    public Product() {
    }

	
    public Product(Brand brand, PStatus PStatus, ProductColor productColor, SubCategory subCategory) {
        this.brand = brand;
        this.PStatus = PStatus;
        this.productColor = productColor;
        this.subCategory = subCategory;
    }
    public Product(Brand brand, PStatus PStatus, ProductColor productColor, SubCategory subCategory, String productCode, String name, Double price, Double discount, Integer qty, Integer reoderLevel, Double weight, String imageUrl1, String imageUrl2, String imageUrl3, String description, Date regDate, Set cartHasProductses) {
       this.brand = brand;
       this.PStatus = PStatus;
       this.productColor = productColor;
       this.subCategory = subCategory;
       this.productCode = productCode;
       this.name = name;
       this.price = price;
       this.discount = discount;
       this.qty = qty;
       this.reoderLevel = reoderLevel;
       this.weight = weight;
       this.imageUrl1 = imageUrl1;
       this.imageUrl2 = imageUrl2;
       this.imageUrl3 = imageUrl3;
       this.description = description;
       this.regDate = regDate;
       this.cartHasProductses = cartHasProductses;
    }
   
    public Integer getIdproduct() {
        return this.idproduct;
    }
    
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public PStatus getPStatus() {
        return this.PStatus;
    }
    
    public void setPStatus(PStatus PStatus) {
        this.PStatus = PStatus;
    }
    public ProductColor getProductColor() {
        return this.productColor;
    }
    
    public void setProductColor(ProductColor productColor) {
        this.productColor = productColor;
    }
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Integer getReoderLevel() {
        return this.reoderLevel;
    }
    
    public void setReoderLevel(Integer reoderLevel) {
        this.reoderLevel = reoderLevel;
    }
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    public String getImageUrl1() {
        return this.imageUrl1;
    }
    
    public void setImageUrl1(String imageUrl1) {
        this.imageUrl1 = imageUrl1;
    }
    public String getImageUrl2() {
        return this.imageUrl2;
    }
    
    public void setImageUrl2(String imageUrl2) {
        this.imageUrl2 = imageUrl2;
    }
    public String getImageUrl3() {
        return this.imageUrl3;
    }
    
    public void setImageUrl3(String imageUrl3) {
        this.imageUrl3 = imageUrl3;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public Set getCartHasProductses() {
        return this.cartHasProductses;
    }
    
    public void setCartHasProductses(Set cartHasProductses) {
        this.cartHasProductses = cartHasProductses;
    }




}


