package pojo;
// Generated Jan 22, 2016 9:21:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductRequestReceipt generated by hbm2java
 */
public class ProductRequestReceipt  implements java.io.Serializable {


     private Integer idproductRequestReceipt;
     private ProductHasVendors productHasVendors;
     private String receiptNo;
     private Date date;

    public ProductRequestReceipt() {
    }

	
    public ProductRequestReceipt(ProductHasVendors productHasVendors) {
        this.productHasVendors = productHasVendors;
    }
    public ProductRequestReceipt(ProductHasVendors productHasVendors, String receiptNo, Date date) {
       this.productHasVendors = productHasVendors;
       this.receiptNo = receiptNo;
       this.date = date;
    }
   
    public Integer getIdproductRequestReceipt() {
        return this.idproductRequestReceipt;
    }
    
    public void setIdproductRequestReceipt(Integer idproductRequestReceipt) {
        this.idproductRequestReceipt = idproductRequestReceipt;
    }
    public ProductHasVendors getProductHasVendors() {
        return this.productHasVendors;
    }
    
    public void setProductHasVendors(ProductHasVendors productHasVendors) {
        this.productHasVendors = productHasVendors;
    }
    public String getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


