package pojo;
// Generated Jan 22, 2016 9:21:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductRequestStatus generated by hbm2java
 */
public class ProductRequestStatus  implements java.io.Serializable {


     private Integer idproductRequestStatus;
     private String status;
     private Set productHasVendorses = new HashSet(0);

    public ProductRequestStatus() {
    }

    public ProductRequestStatus(String status, Set productHasVendorses) {
       this.status = status;
       this.productHasVendorses = productHasVendorses;
    }
   
    public Integer getIdproductRequestStatus() {
        return this.idproductRequestStatus;
    }
    
    public void setIdproductRequestStatus(Integer idproductRequestStatus) {
        this.idproductRequestStatus = idproductRequestStatus;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getProductHasVendorses() {
        return this.productHasVendorses;
    }
    
    public void setProductHasVendorses(Set productHasVendorses) {
        this.productHasVendorses = productHasVendorses;
    }




}


