package pojo;
// Generated Jan 22, 2016 9:21:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductHasVendors generated by hbm2java
 */
public class ProductHasVendors  implements java.io.Serializable {


     private Integer idproductHasVendors;
     private Product product;
     private ProductRequestStatus productRequestStatus;
     private Vendors vendors;
     private String requestQuantity;
     private Set productRequestReceipts = new HashSet(0);

    public ProductHasVendors() {
    }

	
    public ProductHasVendors(Product product, ProductRequestStatus productRequestStatus, Vendors vendors) {
        this.product = product;
        this.productRequestStatus = productRequestStatus;
        this.vendors = vendors;
    }
    public ProductHasVendors(Product product, ProductRequestStatus productRequestStatus, Vendors vendors, String requestQuantity, Set productRequestReceipts) {
       this.product = product;
       this.productRequestStatus = productRequestStatus;
       this.vendors = vendors;
       this.requestQuantity = requestQuantity;
       this.productRequestReceipts = productRequestReceipts;
    }
   
    public Integer getIdproductHasVendors() {
        return this.idproductHasVendors;
    }
    
    public void setIdproductHasVendors(Integer idproductHasVendors) {
        this.idproductHasVendors = idproductHasVendors;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public ProductRequestStatus getProductRequestStatus() {
        return this.productRequestStatus;
    }
    
    public void setProductRequestStatus(ProductRequestStatus productRequestStatus) {
        this.productRequestStatus = productRequestStatus;
    }
    public Vendors getVendors() {
        return this.vendors;
    }
    
    public void setVendors(Vendors vendors) {
        this.vendors = vendors;
    }
    public String getRequestQuantity() {
        return this.requestQuantity;
    }
    
    public void setRequestQuantity(String requestQuantity) {
        this.requestQuantity = requestQuantity;
    }
    public Set getProductRequestReceipts() {
        return this.productRequestReceipts;
    }
    
    public void setProductRequestReceipts(Set productRequestReceipts) {
        this.productRequestReceipts = productRequestReceipts;
    }




}


