package pojo;
// Generated Jan 23, 2016 3:21:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PStatus generated by hbm2java
 */
public class PStatus  implements java.io.Serializable {


     private Integer idpStatus;
     private String state;
     private Set products = new HashSet(0);

    public PStatus() {
    }

    public PStatus(String state, Set products) {
       this.state = state;
       this.products = products;
    }
   
    public Integer getIdpStatus() {
        return this.idpStatus;
    }
    
    public void setIdpStatus(Integer idpStatus) {
        this.idpStatus = idpStatus;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


