package pojo;
// Generated Jan 10, 2016 2:36:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PVotes generated by hbm2java
 */
public class PVotes  implements java.io.Serializable {


     private Integer idpVotes;
     private String status;
     private Set productRatings = new HashSet(0);

    public PVotes() {
    }

    public PVotes(String status, Set productRatings) {
       this.status = status;
       this.productRatings = productRatings;
    }
   
    public Integer getIdpVotes() {
        return this.idpVotes;
    }
    
    public void setIdpVotes(Integer idpVotes) {
        this.idpVotes = idpVotes;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getProductRatings() {
        return this.productRatings;
    }
    
    public void setProductRatings(Set productRatings) {
        this.productRatings = productRatings;
    }




}


