package pojo;
// Generated Jan 23, 2016 3:21:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubCategory generated by hbm2java
 */
public class SubCategory  implements java.io.Serializable {


     private Integer idsubCategory;
     private Catagory catagory;
     private String subCategory;
     private Set products = new HashSet(0);

    public SubCategory() {
    }

	
    public SubCategory(Catagory catagory) {
        this.catagory = catagory;
    }
    public SubCategory(Catagory catagory, String subCategory, Set products) {
       this.catagory = catagory;
       this.subCategory = subCategory;
       this.products = products;
    }
   
    public Integer getIdsubCategory() {
        return this.idsubCategory;
    }
    
    public void setIdsubCategory(Integer idsubCategory) {
        this.idsubCategory = idsubCategory;
    }
    public Catagory getCatagory() {
        return this.catagory;
    }
    
    public void setCatagory(Catagory catagory) {
        this.catagory = catagory;
    }
    public String getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


