package pojo;
// Generated Jan 23, 2016 3:21:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserState generated by hbm2java
 */
public class UserState  implements java.io.Serializable {


     private Integer iduserState;
     private String state;
     private Set users = new HashSet(0);

    public UserState() {
    }

    public UserState(String state, Set users) {
       this.state = state;
       this.users = users;
    }
   
    public Integer getIduserState() {
        return this.iduserState;
    }
    
    public void setIduserState(Integer iduserState) {
        this.iduserState = iduserState;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


