package pojo;
// Generated Jan 23, 2016 3:21:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserGender generated by hbm2java
 */
public class UserGender  implements java.io.Serializable {


     private Integer idgender;
     private String male;
     private String female;
     private Set users = new HashSet(0);

    public UserGender() {
    }

    public UserGender(String male, String female, Set users) {
       this.male = male;
       this.female = female;
       this.users = users;
    }
   
    public Integer getIdgender() {
        return this.idgender;
    }
    
    public void setIdgender(Integer idgender) {
        this.idgender = idgender;
    }
    public String getMale() {
        return this.male;
    }
    
    public void setMale(String male) {
        this.male = male;
    }
    public String getFemale() {
        return this.female;
    }
    
    public void setFemale(String female) {
        this.female = female;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


