package pojo;
// Generated Jan 22, 2016 9:21:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendors generated by hbm2java
 */
public class Vendors  implements java.io.Serializable {


     private Integer idcompanies;
     private String name;
     private String email;
     private String websiteUrl;
     private String address;
     private String cnt1;
     private String cnt2;
     private Set productHasVendorses = new HashSet(0);

    public Vendors() {
    }

    public Vendors(String name, String email, String websiteUrl, String address, String cnt1, String cnt2, Set productHasVendorses) {
       this.name = name;
       this.email = email;
       this.websiteUrl = websiteUrl;
       this.address = address;
       this.cnt1 = cnt1;
       this.cnt2 = cnt2;
       this.productHasVendorses = productHasVendorses;
    }
   
    public Integer getIdcompanies() {
        return this.idcompanies;
    }
    
    public void setIdcompanies(Integer idcompanies) {
        this.idcompanies = idcompanies;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsiteUrl() {
        return this.websiteUrl;
    }
    
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCnt1() {
        return this.cnt1;
    }
    
    public void setCnt1(String cnt1) {
        this.cnt1 = cnt1;
    }
    public String getCnt2() {
        return this.cnt2;
    }
    
    public void setCnt2(String cnt2) {
        this.cnt2 = cnt2;
    }
    public Set getProductHasVendorses() {
        return this.productHasVendorses;
    }
    
    public void setProductHasVendorses(Set productHasVendorses) {
        this.productHasVendorses = productHasVendorses;
    }




}


