/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.text.SimpleDateFormat;
import java.util.Date;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Ashan Nawarathna
 */
public class QtyReqMailGen {

    public static String getReceipt(String venname, String emai, String pname, String pcode, String qty, pojo.ProductHasVendors phv) {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MMM.dd");
        SimpleDateFormat stf = new SimpleDateFormat("hh:mm:ss aa");
        long x = System.currentTimeMillis();
        String lx = x + "";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < lx.length(); i++) {
            sb.append(lx.charAt(i));
            sb.append(classes.randomChar.randomChar());
        }

        String receipt = "<html>\n"
                + "    <head>\n"
                + "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                + "        <title>Quantity Request</title>\n"
                + "    </head>\n"
                + "    <body>\n"
                + "        <div style=\"width: 600px;min-height: 370px;border: 1px solid #CCC;margin: 0 auto;\">\n"
                + "            <div style=\"background-color: palegreen;padding: 5px;height: 50px;\">\n"
                + "                <div style=\"font-size: 18px;font-weight: bold;\">Royal Flowers Stock Management System</div>\n"
                + "                <div>Quantity Request Notification</div>\n"
                + "            </div>\n"
                + "            <div style=\"padding: 5px;font-size: 14px;height: 100px;\">\n"
                + "                <div><span style=\"display: inline-block;width: 70px;\">Vendor</span> :<span>" + venname + "</span> </div>\n"
                + "                <div><span style=\"display: inline-block;width: 70px;\">Email</span> :<span>" + emai + "</span></div>\n"
                + "                <div><span style=\"display: inline-block;width: 70px;\">Receipt No</span> :<span>" + sb.toString() + "</span></div>\n"
                + "                <div style=\"margin-top: 20px;\"> Date : " + sdf.format(date) + " <span style=\"margin-left: 10px;\"></span> Time : " + stf.format(date) + " </div>\n"
                + "            </div>\n"
                + "            <div style=\"padding: 10px;background-color: aliceblue;font-family: consolas;font-size: 14px;height: 150px;\">\n"
                + "                <div style=\"margin-top: 30px;\"><span style=\"display: inline-block;width: 200px;\">Product Name</span> <span>" + pname + "</span></div>\n"
                + "                <div style=\"margin-top: 5px;\"><span style=\"display: inline-block;width: 200px;\">Product Code</span> <span>" + pcode + "</span></div>\n"
                + "                <div style=\"margin-top: 5px;\"><span style=\"display: inline-block;width: 200px;\">Request Quantity</span> <span>" + qty + "</span></div>\n"
                + "            </div>\n"
                + "            <div style=\"text-align: center;font-size: 12px;margin-top: 10px;\">Thank you for your service</div>\n"
                + "            <div style=\"font-size: 10px;padding: 5px;text-align: center;\">This receipt is auto generated by royal flower's stock magt system please contact us for complains or suggestion +94717533368</div>\n"
                + "        </div>\n"
                + "    </body>\n"
                + "</html>";
        Session ses = conn.connector.getSessionFactory().openSession();
        Transaction trans = ses.beginTransaction();
        pojo.ProductRequestReceipt prr = new pojo.ProductRequestReceipt();
        prr.setProductHasVendors(phv);
        prr.setDate(date);
        prr.setReceiptNo(sb.toString());

        ses.save(prr);
        trans.commit();
        ses.close();

        return receipt;

    }
}
